import * as client from 'openid-client';

// Generic, provider-neutral OpenID Connect Relying Party adapter (ADR-0001 section 1). Built on
// `openid-client` (maintained, spec-compliant - panva/openid-client) rather than a hand-rolled
// OAuth/OIDC implementation. Any standards-compliant provider (Auth0, Okta, WorkOS, Google
// Identity Platform, Keycloak, Ory, Zitadel, ...) plugs in purely through configuration:
//   OIDC_ISSUER_URL, OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, OIDC_REDIRECT_URI
// No vendor-specific code lives here. `discovery()` fetches and validates the provider's real
// `.well-known/openid-configuration` document over HTTPS (or HTTP only when explicitly allowed
// for a local/test issuer - see allowInsecureLocalIssuer below, never enabled in production).
//
// Standards followed: OAuth 2.0 Authorization Code Flow with PKCE (S256), `state`, and `nonce`
// (OAuth 2.0 Security BCP, OpenID Connect Core) - all generated by openid-client's own audited
// helpers, never hand-rolled random values reused across requests.

let cachedConfig = null;
let cachedConfigKey = null;

export function isOidcConfigured() {
  return Boolean(process.env.OIDC_ISSUER_URL && process.env.OIDC_CLIENT_ID);
}

function configKey() {
  return `${process.env.OIDC_ISSUER_URL}|${process.env.OIDC_CLIENT_ID}`;
}

// Test-only: a mock issuer used in tests.setup runs on plain HTTP on localhost. Production must
// never set this - discovery() otherwise refuses non-HTTPS issuers by design, which is exactly
// the protection we want against a misconfigured or downgraded production issuer URL.
function allowInsecureLocalIssuer() {
  return process.env.OIDC_ALLOW_INSECURE_ISSUER === 'true' && process.env.NODE_ENV !== 'production';
}

export async function getOidcConfig() {
  if (!isOidcConfigured()) throw new Error('OIDC_NOT_CONFIGURED');
  const key = configKey();
  if (cachedConfig && cachedConfigKey === key) return cachedConfig;
  const issuerUrl = new URL(process.env.OIDC_ISSUER_URL);
  // allowInsecureRequests must be passed as a discovery-time `execute` step, not applied to the
  // Configuration afterward - discovery() itself refuses a non-HTTPS issuer before a
  // Configuration instance even exists to call allowInsecureRequests(config) on. Documented
  // pattern from openid-client's own DiscoveryRequestOptions.execute - see its doc comment.
  const options = allowInsecureLocalIssuer() ? { execute: [client.allowInsecureRequests] } : undefined;
  const config = await client.discovery(issuerUrl, process.env.OIDC_CLIENT_ID, process.env.OIDC_CLIENT_SECRET || undefined, undefined, options);
  cachedConfig = config;
  cachedConfigKey = key;
  return config;
}

export function __resetOidcConfigCacheForTests() { cachedConfig = null; cachedConfigKey = null; }

// Step 1 of the flow: generate PKCE verifier/challenge, state, and nonce (all via openid-client's
// own CSPRNG-backed helpers - see randomPKCECodeVerifier/randomState/randomNonce), and build the
// provider authorization URL. The caller is responsible for persisting {state, nonce,
// codeVerifier} server-side (auth_transactions, keyed by an opaque transaction id in an HttpOnly
// cookie - see routes.auth.mjs) and never trusting anything the browser could tamper with.
export async function startAuthorization({ redirectUri, scope = 'openid email profile' }) {
  const config = await getOidcConfig();
  const codeVerifier = client.randomPKCECodeVerifier();
  const codeChallenge = await client.calculatePKCECodeChallenge(codeVerifier);
  const state = client.randomState();
  const nonce = client.randomNonce();
  const url = client.buildAuthorizationUrl(config, {
    redirect_uri: redirectUri,
    scope,
    code_challenge: codeChallenge,
    code_challenge_method: 'S256',
    state,
    nonce
  });
  return { authorizationUrl: url.href, state, nonce, codeVerifier };
}

// Step 2: exchange the authorization code for tokens, with openid-client itself verifying
// state/nonce match, PKCE, issuer, audience, and ID token signature/expiry (never re-implemented
// by hand here). `currentUrl` must be the exact callback URL including its query string.
export async function completeAuthorization({ currentUrl, expectedState, expectedNonce, codeVerifier }) {
  const config = await getOidcConfig();
  const tokens = await client.authorizationCodeGrant(config, currentUrl, {
    pkceCodeVerifier: codeVerifier,
    expectedState,
    expectedNonce,
    idTokenExpected: true
  });
  const claims = tokens.claims();
  if (!claims || typeof claims.sub !== 'string' || !claims.sub) throw new Error('OIDC_CLAIMS_MISSING_SUBJECT');
  return { claims, issuer: String(process.env.OIDC_ISSUER_URL) };
}
