import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

// Regenerated by `npm run dev` and `npm run build` (never hand-edited or committed) so the
// running app can always show a real, always-current version - see src/release.js's
// VersionBadge. MAJOR comes from package.json's own version field (bump that by hand for a real
// milestone); MINOR/PATCH are derived from the total commit count, so they always advance with
// zero manual bumping and never collide or go backwards.
const major = JSON.parse(readFileSync('package.json', 'utf8')).version.split('.')[0];
const commitCount = Number(execSync('git rev-list --count HEAD').toString().trim());
const minor = String(Math.floor(commitCount / 100)).padStart(2, '0');
const patch = String(commitCount % 100).padStart(2, '0');
const version = `${major}.${minor}.${patch}`;
const commit = execSync('git rev-parse --short HEAD').toString().trim();
const dirty = execSync('git status --porcelain').toString().trim().length > 0;

writeFileSync('public/version.json', JSON.stringify({ version, commit, dirty }, null, 2) + '\n');
console.log(`version.json: ${version}${dirty ? ' (dirty)' : ''} [${commit}]`);
